export const TYPES = {
  Application: Symbol.for("Application"),
  DatabaseService: Symbol.for("DatabaseService"),
  IExceptionFilter: Symbol.for("IExceptionFilter"),
  IPostsController: Symbol.for("IPostsController"),
  IPostsRepository: Symbol.for("IPostsRepository"),
  IPostService: Symbol.for("IPostService"),
  IAuthService: Symbol.for("IAuthService"),
  IAuthController: Symbol.for("IAuthController"),
  IUserRepository: Symbol.for("IUserRepository"),
  IUserService: Symbol.for("IUserService"),
  IConfigService: Symbol.for("IConfigService"),
  IMailerService: Symbol.for("IMailerService"),
  IUserController: Symbol.for("IUserController"),
  ITagController: Symbol.for("ITagController"),
  ITagService: Symbol.for("ITagService"),
  ITagRepository: Symbol.for("ITagRepository"),
  ICommentRepository: Symbol.for("ICommentRepository"),
  ICommentService: Symbol.for("ICommentService"),
  ICommentController: Symbol.for("ICommentController"),
  ILoggerService: Symbol.for("ILoggerService"),
  ISeed: Symbol.for("ISeed"),
  IHealthcheckController: Symbol.for("IHealthcheckController"),
}
